### ISSUE TITLE
getting terminfo into quicklisp

### ISSUE THREAD

**Issue by nikodemus** [npatrick04/terminfo#1]
Currently quicklisp gets terminfo via linedit.

It would be nice if it would be separate. I'm about to update terminfo in linedit from your tree, and started thinking about this.

If you have the energy, I think it would be best if you could be in touch with Paul Foley about this: if he gives his blessing and Xach adds terminfo as a separate entity to quicklisp I'll be happy to remove terminfo from linedit...

**Comment by npatrick04** [comment]
I'm up for it.  I'll start the ball rolling to get terminfo blessed and into quicklisp.

**Comment by nikodemus** [comment]
Thanks. Please be in touch with Paul Foley directly to start with, just so
he is in board.

Cheers,

  -- nikodemus

**Comment by npatrick04** [comment]
Paul is on board.  I made the request to add it into quicklisp.
