### ISSUE TITLE
Use a string in system definition's author field

### ISSUE THREAD

**Issue by alarsyo** [npatrick04/terminfo#2]
Hi, 

while trying to run [Declt](https://github.com/didierverna/declt) on`terminfo` I came across a small issue: 

Declt expects the author field to be a string, not a list, and this looks like the standard for all the libraries inside Quicklisp (in fact, I've only found two that disobey the rule: yours, and [`qmynd`](https://github.com/qitab/qmynd), in the maintainer field).

In [the ASDF manual](https://common-lisp.net/project/asdf/asdf.html#The-defsystem-grammar), these fields seem to be expected to be strings as well.

In an effort to standardize your system definition, would you consider changing this field?

Thanks!

**Comment by npatrick04** [comment]
Fixed.  Sorry for the delay.
c07f107e8d87028f0767a3fe65a5838afdcd052e
