### ISSUE TITLE
Support for 32-bit terminfo files.

### ISSUE THREAD

**Issue by antoszka** [npatrick04/terminfo#3]
Dear Lispers,

it seems that the package doesn't support 32-bit terminfo files. When I try to load the terminfo db with the TERM env variable equal to `screen-256color` I hit this error:

```(let* ((magic (let ((whosit (read-short stream))) 
                (if (= whosit #o432)              
                    whosit                        
                  (error "Invalid file format"))))
```
...which (I assume) is related to this:

```~ file /lib/terminfo/s/screen-256color /lib/terminfo/x/xterm
/lib/terminfo/s/screen-256color: Compiled 32-bit terminfo entry "screen-256color"
/lib/terminfo/x/xterm:           Compiled terminfo entry "xterm"
```
The initial bytes for the other format are `#o542` it seems and probably completely new support has to be written.

**Comment by npatrick04** [comment]
I took a look at it.  The 32-bit extended number format was introduced to support ncurses 6.1 in January.  It does need a fix, but looks like it's only the magic number, and the numbers array updated from 16-bit to 32-bit.

**Comment by antoszka** [comment]
Tako rzecze Nick Patrick (2018-07-11, 20:18):

> I took a look at it.  The 32-bit extended number format was introduced to support ncurses 6.1 in January.  It does need a fix, but looks like it's only the magic number, and the numbers array updated from 16-bit to 32-bit.  

Thanks, I'll see if I can do the fix for you if it's that simple :)

**Comment by npatrick04** [comment]
Go for it.  I got my info from the [Term(5)](http://man7.org/linux/man-pages/man5/term.5.html) manpage.

**Comment by antoszka** [comment]
OK, I'll file a pull request when I'm ready :)

**Comment by npatrick04** [comment]
I went ahead and implemented a fix.  It turns out that the term(5) documentation for the new magic number doesn't match the implementation.  Term(5) states 0542, it's implemented as 01036 (542 in decimal).

9ef7019439abb88554d0ab7d201464ab5da3bf79
